name: moneymate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  intl: ^0.17.0
  
  image_picker: any
  google_mlkit_text_recognition: any

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  google_ml_kit: ^0.18.0
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/playstore.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/playstore.png"
