// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADuP6D5N4oLlS1lN9HC-kjsufCA_EsXy4',
    appId: '1:707128298079:web:5fc594091828961794e9ea',
    messagingSenderId: '707128298079',
    projectId: 'moneymate-995c2',
    authDomain: 'moneymate-995c2.firebaseapp.com',
    storageBucket: 'moneymate-995c2.appspot.com',
    measurementId: 'G-0CMDYZV6RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIY0R8PfwDNgcVPcnCbTHJHGUWZLWXnw',
    appId: '1:707128298079:android:cbec025dd5c4c04e94e9ea',
    messagingSenderId: '707128298079',
    projectId: 'moneymate-995c2',
    storageBucket: 'moneymate-995c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_uqZoVIEOMvDR4CQIkcHtSq6FkiGegM',
    appId: '1:707128298079:ios:1e373bf13b38aace94e9ea',
    messagingSenderId: '707128298079',
    projectId: 'moneymate-995c2',
    storageBucket: 'moneymate-995c2.appspot.com',
    iosBundleId: 'com.example.project3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_uqZoVIEOMvDR4CQIkcHtSq6FkiGegM',
    appId: '1:707128298079:ios:1e373bf13b38aace94e9ea',
    messagingSenderId: '707128298079',
    projectId: 'moneymate-995c2',
    storageBucket: 'moneymate-995c2.appspot.com',
    iosBundleId: 'com.example.project3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADuP6D5N4oLlS1lN9HC-kjsufCA_EsXy4',
    appId: '1:707128298079:web:9d43de4f0da2759694e9ea',
    messagingSenderId: '707128298079',
    projectId: 'moneymate-995c2',
    authDomain: 'moneymate-995c2.firebaseapp.com',
    storageBucket: 'moneymate-995c2.appspot.com',
    measurementId: 'G-1DEK6T7L0D',
  );
}
